export const abbreviateDiscipline = (name: string) => {
    const abbreviations: Record<string, string> = {
        'Administração Financeira e Orçamentária': 'AFO',
        'Direito Administrativo': 'Dir. Adm.',
        'Direito Constitucional': 'Dir. Const.',
        'Língua Portuguesa': 'Português',
        'Tecnologia da Informação': 'TI',
        'Contabilidade Pública': 'Contab. Púb.',
        'Auditoria e Controle Externo': 'Aud. Ext.',
        'Direito Tributário': 'Dir. Trib.',
        'Contabilidade Geral': 'Contab. Ger.',
        'Raciocínio Lógico': 'RLM',
        'Estatística': 'Estat.',
        'Economia': 'Econ.',
        'Administração Pública': 'Adm. Púb.',
        'Tecnologia da Informação e Análise de Dados': 'TI & Dados',
        'Auditoria': 'Auditoria',
        'Controle Externo': 'Controle Ext.',
        'Direito Civil': 'Dir. Civil',
        'Direito Penal': 'Dir. Penal',
        'Direito Processual Civil': 'Proc. Civil',
        'Direito Processual Penal': 'Proc. Penal',
        'Legislação Específica': 'Leg. Esp.',
        'Informática': 'Info',
        'Inglês': 'Inglês',
        'Espanhol': 'Espanhol',
        'Ética': 'Ética',
        'Atualidades': 'Atual.',
        'Contabilidade': 'Contab.',
        'Matemática Financeira': 'Mat. Fin.',
        'Legislação Tributária': 'Leg. Trib.',
        'Legislação Aduaneira': 'Leg. Aduan.',
        'Comércio Internacional': 'Com. Int.',
        'Direito Empresarial': 'Dir. Emp.',
        'Direito Financeiro': 'Dir. Fin.',
        'Direito Previdenciário': 'Dir. Prev.',
        'Direito Eleitoral': 'Dir. Eleit.',
        'Direito do Trabalho': 'Dir. Trab.',
        'Direito Processual do Trabalho': 'Proc. Trab.',
        'Direito Ambiental': 'Dir. Amb.',
        'Direito Internacional': 'Dir. Int.',
        'Direito da Criança e do Adolescente': 'ECA',
        'Direito do Consumidor': 'Consumidor',
        'Direito Agrário': 'Dir. Agr.',
        'Direito Sanitário': 'Dir. San.',
        'Direito Urbanístico': 'Dir. Urb.',
        'Direito Militar': 'Dir. Mil.',
        'Direito Processual Militar': 'Proc. Mil.',
        'Direito Notarial e Registral': 'Notarial',
        'Direito Cooperativo': 'Dir. Coop.',
        'Direito Econômico': 'Dir. Econ.',
        'Direito Marítimo': 'Dir. Marít.',
        'Direito Aéreo': 'Dir. Aéreo',
        'Direito Espacial': 'Dir. Esp.',
        'Direito Canônico': 'Dir. Can.',
        'Direito Romano': 'Dir. Rom.',
        'Direito Comparado': 'Dir. Comp.',
        'Direito Digital': 'Dir. Dig.',
        'Direito da Inovação': 'Inovação',
        'Direito da Propriedade Intelectual': 'Prop. Int.',
        'Direito da Concorrência': 'Concorrência',
        'Direito da Energia': 'Energia',
        'Direito da Mineração': 'Mineração',
        'Direito do Petróleo': 'Petróleo',
        'Direito da Infraestrutura': 'Infra.',
        'Direito da Saúde': 'Saúde',
        'Direito da Educação': 'Educação',
        'Direito da Cultura': 'Cultura',
        'Direito do Desporto': 'Desporto',
        'Direito da Assistência Social': 'Assist. Soc.',
        'Direito da Segurança Pública': 'Seg. Púb.',
        'Direito da Defesa Nacional': 'Defesa Nac.',
        'Direito da Integração': 'Integração',
        'Direito da Globalização': 'Globalização',
        'Direito da Sustentabilidade': 'Sustent.',
        'Direito da Inteligência Artificial': 'Dir. IA',
        'Direito da Biotecnologia': 'Biotec.',
        'Direito da Nanotecnologia': 'Nanotec.',
        'Direito da Robótica': 'Robótica',
        'Direito da Internet': 'Internet',
        'Direito das Telecomunicações': 'Telecom.',
        'Direito dos Transportes': 'Transportes',
        'Direito da Aviação': 'Aviação',
        'Direito da Navegação': 'Navegação',
        'Direito da Pesca': 'Pesca',
        'Direito da Agroindústria': 'Agroind.',
        'Direito da Mineração e Metalurgia': 'Min. Met.',
        'Direito da Construção Civil': 'Const. Civil',
        'Direito da Hotelaria e Turismo': 'Turismo',
        'Direito da Gastronomia': 'Gastronomia',
        'Direito da Moda': 'Moda',
        'Direito do Entretenimento': 'Entreten.',
        'Direito da Arte': 'Arte',
        'Direito da Religião': 'Religião',
        'Direito da Família': 'Família',
        'Direito das Sucessões': 'Sucessões',
        'Direito das Obrigações': 'Obrigações',
        'Direito das Coisas': 'Coisas',
        'Direito dos Contratos': 'Contratos',
        'Direito da Responsabilidade Civil': 'Resp. Civil',
        'Direito da Insolvência': 'Insolvência',
        'Direito da Arbitragem': 'Arbitragem',
        'Direito da Mediação': 'Mediação',
        'Direito da Conciliação': 'Conciliação',
        'Direito da Negociação': 'Negociação',
        'Direito da Gestão de Conflitos': 'Gestão Conf.',
        'Direito da Governança Corporativa': 'Gov. Corp.',
        'Direito da Compliance': 'Compliance',
        'Direito da Ética Empresarial': 'Ética Emp.',
        'Direito da Responsabilidade Social': 'Resp. Soc.',
        'Direito da Diversidade e Inclusão': 'Div. Incl.',
        'Direito da Proteção de Dados': 'LGPD',
        'Direito da Cibersegurança': 'Ciberseg.',
        'Direito da Tecnologia': 'Tecnologia',
        'Direito da Ciência': 'Ciência',
        'Direito da Pesquisa e Desenvolvimento': 'P&D',
        'Direito da Propriedade Industrial': 'Prop. Ind.',
        'Direito da Propriedade Literária e Artística': 'Prop. Lit.',
        'Direito da Propriedade Científica': 'Prop. Cient.',
        'Direito da Propriedade Imaterial': 'Prop. Imat.',
        'Direito da Propriedade Intelectual e Industrial': 'Prop. Int. Ind.',
        'Direito da Propriedade Intelectual na Era Digital': 'Prop. Int. Dig.',
        'Direito da Propriedade Intelectual e Novas Tecnologias': 'Prop. Int. Tec.',
        'Direito da Propriedade Intelectual e Inovação': 'Prop. Int. Inov.',
        'Direito da Propriedade Intelectual e Desenvolvimento': 'Prop. Int. Des.',
        'Direito da Propriedade Intelectual e Sustentabilidade': 'Prop. Int. Sust.',
        'Direito da Propriedade Intelectual e Direitos Humanos': 'Prop. Int. DH',
        'Direito da Propriedade Intelectual e Saúde Pública': 'Prop. Int. Saúde',
        'Direito da Propriedade Intelectual e Educação': 'Prop. Int. Edu.',
        'Direito da Propriedade Intelectual e Cultura': 'Prop. Int. Cult.',
        'Direito da Propriedade Intelectual e Diversidade': 'Prop. Int. Div.',
        'Direito da Propriedade Intelectual e Inclusão': 'Prop. Int. Incl.',
        'Direito da Propriedade Intelectual e Proteção de Dados': 'Prop. Int. Dados',
        'Direito da Propriedade Intelectual e Cibersegurança': 'Prop. Int. Ciber.',
        'Direito da Propriedade Intelectual e Inteligência Artificial': 'Prop. Int. IA',
        'Direito da Propriedade Intelectual e Biotecnologia': 'Prop. Int. Bio.',
        'Direito da Propriedade Intelectual e Nanotecnologia': 'Prop. Int. Nano.',
        'Direito da Propriedade Intelectual e Robótica': 'Prop. Int. Rob.',
        'Direito da Propriedade Intelectual e Internet': 'Prop. Int. Net.',
        'Direito da Propriedade Intelectual e Telecomunicações': 'Prop. Int. Tel.',
        'Direito da Propriedade Intelectual e Transportes': 'Prop. Int. Trans.',
        'Direito da Propriedade Intelectual e Aviação': 'Prop. Int. Avi.',
        'Direito da Propriedade Intelectual e Navegação': 'Prop. Int. Nav.',
        'Direito da Propriedade Intelectual e Pesca': 'Prop. Int. Pesca',
        'Direito da Propriedade Intelectual e Agroindústria': 'Prop. Int. Agro.',
        'Direito da Propriedade Intelectual e Mineração': 'Prop. Int. Min.',
        'Direito da Propriedade Intelectual e Construção Civil': 'Prop. Int. Const.',
        'Direito da Propriedade Intelectual e Turismo': 'Prop. Int. Tur.',
        'Direito da Propriedade Intelectual e Gastronomia': 'Prop. Int. Gast.',
        'Direito da Propriedade Intelectual e Moda': 'Prop. Int. Moda',
        'Direito da Propriedade Intelectual e Entretenimento': 'Prop. Int. Ent.',
        'Direito da Propriedade Intelectual e Arte': 'Prop. Int. Arte',
        'Direito da Propriedade Intelectual e Religião': 'Prop. Int. Rel.',
        'Direito da Propriedade Intelectual e Família': 'Prop. Int. Fam.',
        'Direito da Propriedade Intelectual e Sucessões': 'Prop. Int. Suc.',
        'Direito da Propriedade Intelectual e Obrigações': 'Prop. Int. Obr.',
        'Direito da Propriedade Intelectual e Coisas': 'Prop. Int. Coisas',
        'Direito da Propriedade Intelectual e Contratos': 'Prop. Int. Cont.',
        'Direito da Propriedade Intelectual e Responsabilidade Civil': 'Prop. Int. Resp.',
        'Direito da Propriedade Intelectual e Insolvência': 'Prop. Int. Ins.',
        'Direito da Propriedade Intelectual e Arbitragem': 'Prop. Int. Arb.',
        'Direito da Propriedade Intelectual e Mediação': 'Prop. Int. Med.',
        'Direito da Propriedade Intelectual e Conciliação': 'Prop. Int. Conc.',
        'Direito da Propriedade Intelectual e Negociação': 'Prop. Int. Neg.',
        'Direito da Propriedade Intelectual e Gestão de Conflitos': 'Prop. Int. Gest.',
        'Direito da Propriedade Intelectual e Governança Corporativa': 'Prop. Int. Gov.',
        'Direito da Propriedade Intelectual e Compliance': 'Prop. Int. Comp.',
        'Direito da Propriedade Intelectual e Ética Empresarial': 'Prop. Int. Ética',
        'Direito da Propriedade Intelectual e Responsabilidade Social': 'Prop. Int. Soc.',
        'Direito da Propriedade Intelectual e Diversidade e Inclusão': 'Prop. Int. Div. Incl.',
        'Direito da Propriedade Intelectual e Proteção de Dados e Cibersegurança': 'Prop. Int. Dados. Ciber.',
        'Direito da Propriedade Intelectual e Inteligência Artificial e Robótica': 'Prop. Int. IA. Rob.',
        'Direito da Propriedade Intelectual e Biotecnologia e Nanotecnologia': 'Prop. Int. Bio. Nano.',
        'Direito da Propriedade Intelectual e Internet e Telecomunicações': 'Prop. Int. Net. Tel.',
        'Direito da Propriedade Intelectual e Transportes e Aviação': 'Prop. Int. Trans. Avi.',
        'Direito da Propriedade Intelectual e Navegação e Pesca': 'Prop. Int. Nav. Pesca',
        'Direito da Propriedade Intelectual e Agroindústria e Mineração': 'Prop. Int. Agro. Min.',
        'Direito da Propriedade Intelectual e Construção Civil e Turismo': 'Prop. Int. Const. Tur.',
        'Direito da Propriedade Intelectual e Gastronomia e Moda': 'Prop. Int. Gast. Moda',
        'Direito da Propriedade Intelectual e Entretenimento e Arte': 'Prop. Int. Ent. Arte',
        'Direito da Propriedade Intelectual e Religião e Família': 'Prop. Int. Rel. Fam.',
        'Direito da Propriedade Intelectual e Sucessões e Obrigações': 'Prop. Int. Suc. Obr.',
        'Direito da Propriedade Intelectual e Coisas e Contratos': 'Prop. Int. Coisas. Cont.',
        'Direito da Propriedade Intelectual e Responsabilidade Civil e Insolvência': 'Prop. Int. Resp. Ins.',
        'Direito da Propriedade Intelectual e Arbitragem e Mediação': 'Prop. Int. Arb. Med.',
        'Direito da Propriedade Intelectual e Conciliação e Negociação': 'Prop. Int. Conc. Neg.',
        'Direito da Propriedade Intelectual e Gestão de Conflitos e Governança Corporativa': 'Prop. Int. Gest. Gov.',
        'Direito da Propriedade Intelectual e Compliance e Ética Empresarial': 'Prop. Int. Comp. Ética',
        'Direito da Propriedade Intelectual e Responsabilidade Social e Diversidade e Inclusão': 'Prop. Int. Soc. Div. Incl.'
    };

    if (abbreviations[name]) return abbreviations[name];

    // Try to extract from parentheses
    const parenMatch = name.match(/\(([^)]+)\)/);
    if (parenMatch) return parenMatch[1];

    // If it's a "Direito X", abbreviate to "Dir. X"
    if (name.startsWith('Direito ')) {
        return 'Dir. ' + name.substring(8, 18) + (name.length > 18 ? '...' : '');
    }

    // Fallback: aggressive truncation
    if (name.length > 12) {
        return name.substring(0, 10) + '...';
    }

    return name;
};
